---
# maintains versions and can overwrite all.yml
namada:
  validator:
    version: v201.0.7
    chain_id: namada.5f5de2dd1b88cba30586420
    network_config_server: https://github.com/anoma/namada-mainnet-genesis/releases/download/mainnet-genesis
    cometbft:
      version: 0.37.16
    rust:
      version: 1.85.1
  snapshot_url: https://server-3.itrocket.net/mainnet/namada/namada_2025-10-22_4004870_snap.tar.lz4
